import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CoinGecko from 'coingecko-api/lib/CoinGecko';

const coinGeckoClient = new CoinGecko();

export default function Home(props) {
  const { data } = props.result;
  return (
    <div className={styles.container}>
      <Head>
        <title>Market Prices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Market Prices</h1>
      <table className='table'>
        <thead>
          <th>Symbol</th>
          <th>24H Change</th>
          <th>Price</th>
          <th>Market Cap</th>
        </thead>
        <tbody>
          {data.map(coin => (
            <tr key={coin.id}>
              <td>
                <img src={coin.image}
                  style={{ width: "25px", height: "25px" }}>
                </img>
                {coin.symbol.toUpperCase()}</td>
              <td>{coin.price_change_percentage_24h}</td>
              <td>{coin.current_price}</td>
              <td>{coin.market_cap}</td>
            </tr>
          ))}
        </tbody>
      </table>

    </div>
  )
}

export async function getServerSideProps(context) {
  const params = {
    order: CoinGecko.ORDER.MARKET_CAP_DESC
  }
  const result = await coinGeckoClient.coins.markets({ params });
  return {
    props: {
      result
    }
  }
}
